title: Lucas Walters  # Name of the site
author:
  name: Lucas Walters
metadata:
    description: 'My personal website.'

# Header customization
header:
  title: <span>L</span><span>U</span><span>C</span><span>A</span><span>S</span> <span id="new-word"> </span><span>W</span><span>A</span><span>L</span><span>T</span><span>E</span><span>R</span><span>S</span>
  description: <h3><div id="hero-description">Software Engineering Student</div></h3>
  buttons:
    - text: "More info"
      link: "#introduction"
      class: "learn-more-btn"

footer:
  links:
    - text: ""
